# Generated by Django 4.2.7 on 2023-11-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipename', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('cuisines', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=100)),
                ('preptime', models.CharField(max_length=100)),
                ('cooktime', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=100)),
                ('directions', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
