# Generated by Django 4.2.7 on 2023-11-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusine', '0002_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
